config/routes.rb
App::Application.routes.draw do
  root to: 'definities#index'

  resources :definitions, controller: 'definities',
                          path: 'definities',
                          only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'woordvandedag', as: :wotd, on: :collection
    get 'term/:term', as: :term, on: :collection, action: :term
    get 'search', as: :search, on: :collection, action: :search
    get 'begintmet/:prefix', as: :prefix, on: :collection, action: :prefix
    post 'autocomplete', on: :collection, action: :auto_complete_for_definition_q

    get 'random', as: :random, on: :collection, action: :random
    get 'top', as: :top, on: :collection, action: :top
    get 'recent', as: :recent, on: :collection, action: :recent

    get 'wijzigingen', as: :recent_edits, on: :collection, action: :wijzigingen
    get 'reacties', as: :recent_reactions, on: :collection, action: :reacties

    get 'geschiedenis', as: :history, on: :member, action: :history
    post 'thumbsup', on: :member, action: :thumbsup

    # TODO: reactions should really be their own (sub) controller
    post 'reactie', as: :post_reaction, on: :member, action: :add_reaction
    delete 'reactie/:reaction_id', as: :reaction, on: :collection, action: :delete_reactie

    post 'newwotd', as: :new_wotd, on: :member, action: :new_wotd
  end

  resource :info, controller: 'info', only: [:show] do
    get :contact, on: :collection
    get :regios, on: :collection
    get :feeds, on: :collection
    get :updates, on: :collection
  end

  post 'login', controller: :account, as: :login
  get 'login', controller: :account
  get 'logout', controller: :account, as: :logout
  resource :account, controller: 'account', only: [:new, :create, :edit, :update]

  resources :users, controller: 'gebruiker', id: /.*/, only: [:index] do
    get 'wijzigingen', as: :edits, on: :member, action: :edits
    get 'reacties', as: :reactions, on: :member, action: :reactions
  end
  get '/users/:id' => 'gebruiker#show', as: :user, id: /.*/

  resources :posts, controller: 'post', only: [:index, :new, :create, :show] do
    get 'outbox', as: :outbox, on: :collection, action: :outbox
  end

  get '/recent.xml' => 'definities#recent_rss'
  get '/wijzigingen.xml' => 'definities#wijzigingen_rss', as: :recent_edits_rss
  get '/woordvandedag.xml' => 'definities#woordvandedag'

  get 'robots.txt' => 'utils#robots'
end

app/controllers/definities_controller.rb
class DefinitiesController < ApplicationController
  before_action :login_required, :only => [:new, :create, :edit, :update, :destroy, :add_reaction, :delete_reaction, :new_wotd]

  before_action :find_definition, only: [:toon, :show, :edit, :update, :history, :destroy, :add_reaction, :thumbsup, :new_wotd]
  before_action :set_title_from_definition, only: [:show, :edit, :update, :history, :add_reaction]

  before_action :find_or_init_voter, only: [:thumbsup]

  include AutoComplete
  auto_complete_for :definition, :q, search_column: 'word'

  def index
    @title = "Welkom bij het Vlaams woordenboek"
    @random_definitions = Definition.preload(:created_by, :last_edited_by, :wotds).random_sample(count: 5, needs_positive_rating: true)
  end

  def search
    unless params[:definition] && params[:definition][:q]
      redirect_to root_path
      return
    end

    @q = params[:definition][:q]
    @definitions = Definition.preload(:created_by, :last_edited_by, :wotds).search @q
    @title = "Zoekresultaten voor '#{@q}'"
  end

  def prefix
    @begin = params[:prefix]
    unless read_fragment(:controller => 'definities', :action => 'prefix', :prefix => @begin, :part => 'lijst')

      prefixes_to_check = ('a'..'z').map { |letter| "\"#{@begin}#{letter}\"" }
      @langer_counts = Definition.
        joins("JOIN JSON_TABLE('[#{prefixes_to_check.join(',')}]', '$[*]' COLUMNS(prefix VARCHAR(255) PATH '$')) prefixes ON definitions.word LIKE CONCAT(prefixes.prefix, '%')").
        order('prefixes.prefix').
        group('prefixes.prefix').
        count

      @words = Definition.where('word LIKE ?', "#{@begin}%").
               order(word: :asc).
               preload(:created_by, :last_edited_by, :wotds).
               distinct.
               pluck(:word)
    end
    @title = "Woorden die beginnen met '" + @begin + "'"
  end

  def woordvandedag
    @title = "Vlaams woord van de dag"

    @offset = params[:offset].to_i || 0
    @wotds = Wotd.all.past.preload(definition: [:created_by, :last_edited_by, :wotds]).limit(20).offset(@offset)
    if logged_in? && current_user.admin?
      @upcoming_wotds = Wotd.where("date > ?", Date.today).order('date ASC')
    end

    respond_to do |format|
      format.html {}
      format.xml do
        @feed_title = "Vlaams woord van de dag"
        @feed_url = "http://" + request.host_with_port + "/definities/woordvandedag"
        @feed_description = "Vlaams woord van de dag"
        response.headers['Content-Type'] = 'application/rss+xml'
        render 'woordvandedag', layout: false
      end
    end
  end

  def show
    if logged_in? && current_user.admin?
      @wotds = Wotd.where(definition: @definition)
      @wotd_dates = []

      (Date.today..(Date.today+50)).each do |date|
        datestr = date.strftime("%Y-%m-%d")
        wotd = Wotd.find_by(date: datestr)
        if !wotd
          @wotd_dates << datestr
        end
      end
    end

    render 'toon'
  end

  alias :toon :show

  def term
    @term = params[:term]
    @definitions = Definition.where(word: @term).preload(:created_by, :last_edited_by, :wotds).order(positivevotes: :desc)

    @title = @term
  end

  def random
    @title = "Een willekeurige selectie"
    @random_definitions = Definition.random_sample(count: 10).preload(:created_by, :last_edited_by, :wotds).order(:positivevotes)
  end

  def recent
    @offset = 0
    if params[:offset]
      @offset = params[:offset]
    end
    @title = "Recente toevoegingen"
    @recent_definitions = Definition.preload(:created_by, :last_edited_by, :wotds).recent(count: 20, offset: @offset)
  end

  def wijzigingen
    @offset = 0
    if params[:offset]
      @offset = params[:offset]
    end
    @title = "Recente wijzigingen"
    @definition_versions = DefinitionVersion.recent(count: 20, offset: @offset)
  end

  def reacties
    @offset = 0
    if params[:offset]
      @offset = params[:offset]
    end
    @title = "Recente reacties"
    @reactions = Reaction.recent(count: 20, offset: @offset)
  end

  def top
    @offset = 0
    if params[:offset]
      @offset = params[:offset]
    end
    @title = "Top woorden"

    @top_definitions = Definition.preload(:created_by, :last_edited_by, :wotds).top(count: 20, offset: @offset)
  end

  def new
    @definition = Definition.new
    @title = "Voeg een nieuwe definitie toe"
  end

  def create
    @definition = Definition.new(new_definition_params)
    @definition.updated_by = self.current_user.id
    @definition.rating = 0;
    if @definition.save
      flash[:notice] = 'Uw nieuwe term werd succesvol in onze databank bewaard. Bedankt voor uw bijdrage!'
      redirect_to term_definitions_path(@definition.word)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @definition.updated_by = self.current_user.id
    if @definition.update(edit_definition_params)
      flash[:notice] = 'Uw aanpassing werd succesvol in onze databank bewaard. Bedankt voor uw bijdrage.'
      redirect_to term_definitions_path(term: @definition.word)
    else
      render 'edit'
    end
  end

  def destroy
    if self.current_user.admin?
      @definition.destroy
      flash[:notice] = 'Uw beschrijving werd verwijderd.'
    else
      flash[:notice] = 'Woorden kunnen niet worden verwijderd'
    end
    redirect_to term_definitions_path(term: @definition.word)
  end

  def history
    @definition_versions = @definition.versions.reverse
  end

  def thumbsup
    unless Vote.where(definition_id: @definition, voter_id: @voter.id).exists?
      @vote = Vote.create(:definition => @definition, :voter => @voter, :value => 1)
      @definition.increment!(:positivevotes)
    end

    respond_to do |format|
      format.js { render 'thumbsup' }
      format.html { redirect_to definition_path(@definition) }
    end
  end

  def add_reaction
    @reaction = Reaction.new(reaction_params)
    @reaction.definition = @definition
    @reaction.created_by = self.current_user.id
    if @reaction.save
      flash[:notice] = 'Bedankt voor uw reactie!'
      redirect_to definition_path(@definition)
    else
      render 'toon'
    end
  end

  def delete_reactie
    @reaction = Reaction.find(params[:reaction_id])
    if self.current_user.admin?
      @reaction.destroy
      flash[:notice] = 'Uw reactie werd verwijderd.'
    else
      flash[:notice] = 'Reacties kunnen niet worden verwijderd'
    end
    redirect_to definition_path(@reaction.definition)
  end

  def new_wotd
    if logged_in? && current_user.admin?
      @wotd = Wotd.new(date: params[:date], definition: @definition)
      if @wotd.save
        flash[:notice] = 'Definitie bewaard voor WOTD'
      end
    end
    redirect_to definition_path(@definition)
  end

  def recent_rss
    @definitions = Definition.recent(count: 10)
    @feed_title = "Vlaams woordenboek: Recente toevoegingen"
    @feed_url = "http://" + request.host_with_port
    @feed_description = "Recent toegevoegde woorden aan het Vlaams Woordenboek"
    response.headers['Content-Type'] = 'application/rss+xml'
    render 'recent'
  end

  def wijzigingen_rss
    @definition_versions = DefinitionVersion.recent(count: 10)
    @feed_title = "Vlaams woordenboek: Recente wijzigingen"
    @feed_url = "http://" + request.host_with_port
    @feed_description = "Recent toegevoegde woorden aan het Vlaams Woordenboek"
    response.headers['Content-Type'] = 'application/rss+xml'
    render 'recent_changes'
  end

  private

  def set_title_from_definition
    @title = @definition.word
  end

  def find_definition
    @definition = Definition.find(params[:id])
  end

  def find_or_init_voter
    @voter ||= if cookies[:voter]
                 Voter.find cookies[:voter]
               else
                 current_voter = Voter.create!
                 cookies[:voter] = { :value => current_voter.id.to_s, :expires => 1.year.from_now }
                 current_voter
               end
  end

  def new_definition_params
    params.require(:definition).permit(
      :word,
      :properties,
      :description,
      :regio,
      :example
    )
  end

  def edit_definition_params
    params.require(:definition).permit(
      :word,
      :properties,
      :description,
      :regio,
      :example
    )
  end

  def reaction_params
    params.require(:reaction).permit(
      :title,
      :body
    )
  end
end

app/helpers/definities_helper.rb
module DefinitiesHelper
end

app/views/definities/_definition_version.html.erb
<div class="formfield" style="border: solid #ddd 1px;padding: 10px 10px 10px 10px;background-color: #fff8f0">
	<h2>
		<%= link_to definition_version.word, term_definitions_path(term: definition_version.word) %>
		<% if definition_version.properties.size > 0 %>
			<div class="small">(<%= definition_version.properties %>)</div>
		<% end %>
	</h2>
	<%= format_user_content(definition_version.description) %>
	<i><%= format_user_content(definition_version.example) %></i>
	<div class="right">
		<div class="caption">
			<% if definition_version.regio == 0 %>
				Gans Vlaanderen
			<% elsif definition_version.regio % 100 == 0 %>
				Provincie <%= Regio::REGIO[definition_version.regio] %>
			<% else %>
				Regio <%= Regio::REGIO[definition_version.regio] %>
			<% end %>
		</div>
	</div>
	<div class="caption">
			Bewerking door
			<% if definition_version.editor %>
				<%= link_to user_path(definition_version.editor.login) do %>
					<%= definition_version.editor.login %>
				<% end %>
			<% else %>
				Verwijderde gebruiker
			<% end %>
			op
			<%=
				localize( definition_version.updated_at, format = '%d %b %Y %H:%M' )
			%><br/>
			<%= link_to definition_version.definition.reactions.size.to_s + " reactie(s)", definition_path(definition_version.definition) %>
			<% if logged_in? %>
				&nbsp;|&nbsp; <%= link_to "bewerk", edit_definition_path(definition_version.definition) %>
				<% if current_user.admin? %>
					&nbsp;|&nbsp; <%= link_to "verwijder", definition_path(definition_version.definition), method: :delete %>
				<% end %>
			<% end %>
	</div>
</div>

app/views/definities/_form.html.erb
<!--[form:definition]-->

<div class="formfield">
	<label for="definition_word">Woord<span style="color:#ff0000;">*</span></label>
	<div class="caption">
		Het woord, term of de uitspraak die hier wordt gedefinieerd. Gebruik liefst geen hoofdletters.
	</div>
	<%= form.text_field :word %>
</div>

<div class="formfield">
	<label for="definition_properties">Kenmerken</label>
	<div class="caption">
		Geef eventueel een aantal woordkenmerken aan<br>
		- Geef bijvoorbeeld "de ~ (v.), ~sen" aan om het lidwoord, geslacht en meervoud van een zelfstandig naamwoord op te geven<br/>
		- Dit veld is niet verplicht in te vullen
	</div>
	<%= form.text_field :properties  %>
</div>

<div class="formfield">
	<label for="definition_description">Beschrijving<span style="color:#ff0000;">*</span></label>
	<div class="caption">
		Geef een beschrijving van de term.<br/>
		- Gebruik "Algemeen Beschaafd Vlaams" om het woord te beschrijven<br>
		- Beschrijf slechts 1 betekenis, voeg andere apart toe<br/>
		- Gebruik vierkante haakjes om een ander woord te linken, zo wordt [goesting] omgezet naar <%= link_to 'goesting', term_definitions_path(term: 'goesting') %>
	</div>
	<%= form.text_area :description, :size => '60x10'  %>
</div>

<div class="formfield">
	<label for="definition_word">Regio</label>
	<div class="caption">
		Indien het woord enkel in een lokaal dialect wordt gebruikt, geef dan ook de streek aan waar deze term wordt gebruikt<br/>
		- <%= link_to "Meer info over de regio's.", regios_info_path %>
	</div>
	<%= form.select :regio, Regio::OPTIONS.collect { |option| [option.type_name, option.options.collect { |option| [option.name, option.id] }] } %>
</div>

<div class="formfield">
	<label for="definition_example">Voorbeeld<span style="color:#ff0000;">*</span></label>
	<div class="caption">
		Geef een voorbeeldzin met het woord. <br/>
		- Gebruik ook hier weer "Algemeen Beschaafd Vlaams"<br/>
		- Zorg dat de bovenstaande betekenis van het woord verduidelijkt wordt<br/>
		- Hier kan je ook vierkante haakjes gebruiken om te linken naar andere woorden
	</div>
	<%= form.text_area :example, :size => '60x10'  %>
</div>

<!--[eoform:definition]-->

<p>Uw inbreng wordt geweldig geapprecieerd!</p>

<div class="caption">Velden met <span style="color:#ff0000;">*</span> moeten worden ingevuld</div>

app/views/definities/_reactionform.html.erb
<!--[form:reaction]-->

<div class="formfield">
  <label for="reaction_title">Titel</label>
  <div class="caption">
    De titel van uw reactie
  </div>
  <%= reactionform.text_field :title %>
</div>

<div class="formfield">
  <label for="reaction_body">Reactie</label>
  <div class="caption">
    Geef hier uw reactie op de bovenstaande definitie.<br/>
  </div>
  <%= reactionform.text_area :body, :size => '60x10'  %>
</div>

<!--[eoform:reaction]-->

<p>Uw inbreng wordt geweldig geapprecieerd!</p>

app/views/definities/_secondarymenu.html.erb
<p>
  <%= link_to 'Wees welgekomen', root_path %>
  | <%= link_to 'Willekeurig', random_definitions_path %>
  | <%= link_to 'Top woorden', top_definitions_path %>
  | <%= link_to 'Recent', recent_definitions_path %>
  <% if logged_in? %>
  | <%= link_to 'Voeg een term toe', new_definition_path %>
  <% end %>
</p>

app/views/definities/edit.html.erb
<p>Met het volgende formulier kunt ge uw beschrijving aanpassen.</p>

<%= form_for @definition do |form| %>
  <%= render partial: 'form', object: form %>
  <%= submit_tag 'Bewerk' %>
<% end %>

app/views/definities/history.html.erb
<p>De beschrijving van deze term werd <%= @definition_versions.size %> keer aangepast.</p>

<% if @definition_versions.size > 0 %>
	<% @definition_versions.each do |definition_version| %>
		<h2>Versie <%= definition_version.version %></h2>
		<%= render partial: "definition_version", object: definition_version %>
	<% end %>
<% end %>

app/views/definities/new.html.erb
<p>Ingelogde gebruikers kunnen nieuwe termen en hun definities aan het Vlaamse woordenboek toevoegen.</p>

<% if logged_in? %>

	<p>Met het volgende formulier kunt ge nieuwe beschrijvingen van typisch Vlaamse woorden, termen en uitspraken toevoegen aan onze
	databank.</p>

	<%= form_for Definition.new do |form| %>
		<%= render partial: 'form', object: form %>
		<%= submit_tag "Creëer" %>
	<% end %>

<% else %>

	<%= render :partial => "account/login" %>

<% end %>

app/views/definities/prefix.html.erb
<% cache( :controller => 'definities', :action => 'prefix', :id => @begin, :part => 'lijst' ) do %>

  <% if @langer_counts.size > 0 %>
    <div class="block">
      <ol class="prefix-list">
        <% @langer_counts.each_pair do |prefix, count| %>
          <li><%= link_to "#{prefix} (#{count})", prefix_definitions_path(prefix: prefix) %></li>
        <% end %>
      </ol>
    </div>
  <% end %>

  <% if @words.size > 0 %>

    <p>De volgende <%= @words.size %> termen in onze databank beginnen met '<%=@begin%>':<p>

    <div class="prefix-columns" %>
      <% @words.each do |word| %>
        <%= link_to word, term_definitions_path(term: word) %> <br />
      <% end %>
    </div>

  <% else %>

    <p> De databank bevat geen termen die beginnen met '<%=@begin%>'</p>

  <% end %>

<% end %>

app/views/definities/random.html.erb
<p>Dit is een willekeurige selectie woorden van wat het Vlaams woordenboek zoal te bieden heeft. Herlaad voor <%= link_to 'meer', random_definitions_path %>.</p>

<% @random_definitions.each do |definition| %>
  <%= render partial: 'definition', object: definition %>
<% end %>

app/views/definities/reacties.html.erb
<p>De onderstaande reacties zijn de laatst toegevoegde reacties op termen in ons woordenboek. </p>

<% counter = 1 %>
<% @reactions.each do |reaction| %>
  <h2>#<%= @offset.to_i + counter %>
    <%= link_to reaction.definition.word, definition_path(reaction.definition) %>
  </h2>
  <% counter = counter + 1 %>

  <%= render partial: 'reaction', object: reaction %>
<% end %>

<p>
  <%= link_to 'Meer ...', recent_reactions_definitions_path(offset: @offset.to_i + 20) %>
</p>

app/views/definities/search.html.erb
<% if @definitions.size > 0 %>
  <p>Uw vraag naar "<%= @q %>" leverde de volgende resultaten op:</p>
  <% @definitions.each do |definition| %>
    <%= render partial: 'definition', object: definition %>
  <% end %>
<% else %>
  <p>Uw vraag naar "<%= @q %>" leverde helaas geen resultaten op.</p>
<% end %>

<h2>Voeg een nieuw item toe aan onze databank!</h2>

<p>Niet gevonden wat ge zocht? Als ingelogd gebruiker kunt ge hier vanalle vlaamstalige dingens en hun betekenis toevoegen aan onze databank.</p>

<% if logged_in? %>

  <% form_for Definition.new(word: @q) do |form| %>
    <%= render partial: 'form', object: form %>
    <%= submit_tag "Voeg mijn definitie toe" %>
  <% end %>

<% else %>

  <%= render :partial => "account/login" %>

<% end %>

app/views/definities/term.html.erb
<% unless @definitions.empty? %>
  <p>Onze databank bevat de volgende beschrijving(en) van "<%=@term%>"</p>
  <% @definitions.each do |definition| %>
    <%= render partial: "definition", object: definition %>
  <% end %>
<% else %>
  <p>Er zijn nog geen beschrijvingen van "<%= @term %>" in onze databank.</p>
<% end %>

<h2>Voeg een nieuwe beschrijving toe aan onze databank!</h2>

<p>Weet ge nog een andere betekenis voor deze term? Als ingelogd gebruiker kunt ge uw eigen beschrijvingen van Vlaamse woorden en
uitspraken in onze databank aanvullen. Om fouten te verbeteren klikt ge bij de bovenstaande definities op de "bewerk" link, en om te
reageren op een definitie klikt ge op de "reacties" link.</p>

<% if logged_in? %>

  <%= form_for Definition.new do |form| %>
    <%= render partial: 'form', object: form %>
    <%= submit_tag "Voeg mijn definitie toe" %>
  <% end %>

<% else %>

  <%= render :partial => "account/login" %>

<% end %>

app/views/definities/thumbsup.js.erb
document.querySelector('#definition-<%= @definition.id %>-positive').innerHTML = '<%= @definition.positivevotes %>'
//document.querySelector('#definition-<%= @definition.id %>-negative').innerHTML = '<%= @definition.negativevotes %>'

app/views/definities/woordvandedag.html.erb
<p>
  Dagelijks kiezen we een woord van de dag, uit de vele plezante woorden die in dit Vlaams woordenboek terug te vinden zijn.
  Het Vlaams woord van de dag is ook beschikbaar als
  <%= link_to wotd_definitions_path(format: 'xml') do %>
    RSS Feed <%= image_tag 'rss.png', alt: 'RSS' %>
  <% end %>
</p>

<% if logged_in? && current_user.admin? %>
  <div class="block-admin">
    <h3>Wachtrij</h3>
    <ul>
      <% @upcoming_wotds.each do |wotd| %>
        <li><%= localize wotd.date, "%d %B %Y" %>: <%= link_to wotd.definition.word, definition_path(wotd.definition) %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<% @wotds.each_with_index do |wotd, counter| %>
  <h2>#<%= @offset.to_i + counter + 1 %> <%= localize wotd.date, "%d %B %Y" %>: <%= wotd.definition.word %></h2>
  <%= render partial: 'definition', object: wotd.definition %>
<% end %>

<p>
  <%= link_to 'Meer ...', wotd_definitions_path(offset: @offset + 20) %>
</p>