config/routes.rb
App::Application.routes.draw do
  root to: 'definities#index'

  resources :definitions, controller: 'definities',
                          path: 'definities',
                          only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'woordvandedag', as: :wotd, on: :collection
    get 'term/:term', as: :term, on: :collection, action: :term
    get 'search', as: :search, on: :collection, action: :search
    get 'begintmet/:prefix', as: :prefix, on: :collection, action: :prefix
    post 'autocomplete', on: :collection, action: :auto_complete_for_definition_q

    get 'random', as: :random, on: :collection, action: :random
    get 'top', as: :top, on: :collection, action: :top
    get 'recent', as: :recent, on: :collection, action: :recent

    get 'wijzigingen', as: :recent_edits, on: :collection, action: :wijzigingen
    get 'reacties', as: :recent_reactions, on: :collection, action: :reacties

    get 'geschiedenis', as: :history, on: :member, action: :history
    post 'thumbsup', on: :member, action: :thumbsup

    # TODO: reactions should really be their own (sub) controller
    post 'reactie', as: :post_reaction, on: :member, action: :add_reaction
    delete 'reactie/:reaction_id', as: :reaction, on: :collection, action: :delete_reactie

    post 'newwotd', as: :new_wotd, on: :member, action: :new_wotd
  end

  resource :info, controller: 'info', only: [:show] do
    get :contact, on: :collection
    get :regios, on: :collection
    get :feeds, on: :collection
    get :updates, on: :collection
  end

  post 'login', controller: :account, as: :login
  get 'login', controller: :account
  get 'logout', controller: :account, as: :logout
  resource :account, controller: 'account', only: [:new, :create, :edit, :update]

  resources :users, controller: 'gebruiker', id: /.*/, only: [:index] do
    get 'wijzigingen', as: :edits, on: :member, action: :edits
    get 'reacties', as: :reactions, on: :member, action: :reactions
  end
  get '/users/:id' => 'gebruiker#show', as: :user, id: /.*/

  resources :posts, controller: 'post', only: [:index, :new, :create, :show] do
    get 'outbox', as: :outbox, on: :collection, action: :outbox
  end

  get '/recent.xml' => 'definities#recent_rss'
  get '/wijzigingen.xml' => 'definities#wijzigingen_rss', as: :recent_edits_rss
  get '/woordvandedag.xml' => 'definities#woordvandedag'

  get 'robots.txt' => 'utils#robots'
end

app/controllers/gebruiker_controller.rb
class GebruikerController < ApplicationController
  before_action :find_user, only: [:show, :reactions, :edits]

  def index
    @title = "Gebruikers"
    @topeditors = User.connection.select_all "select count(updated_by) as c, updated_by from definition_versions group by updated_by order by c desc limit 10;"
    @activeeditors = User.connection.select_all "select count(updated_by) as c, updated_by from definition_versions where updated_at > '#{1.week.ago.to_s(:db)}' group by updated_by order by c desc limit 10;"
    @activeeditors = @topeditors if @activeeditors.empty? # Just failsafe mostly for development where there might be no recent edits
    @topreactors = User.connection.select_all "select count(created_by) as c, created_by from reactions group by created_by order by c desc limit 10;"
    @recentusers = User.order('id DESC').limit(5)
  end

  def show
    @title = @user.login
    @reactions = Reaction.where(created_by: @user.id).order('created_at DESC').limit(5)
    @definition_versions = DefinitionVersion.where(updated_by: @user.id).order('updated_at DESC').limit(5)
  end

  def reactions
    @title = 'Reacties van ' + @user.login
    @reactions = Reaction.where(created_by: @user.id).
                 order('created_at DESC').
                 paginate(page: current_page, per_page: 5)
  end

  def edits
    @title = 'Wijzigingen door ' + @user.login
    @definition_versions = DefinitionVersion.where(updated_by: @user.id).
                           order('updated_at DESC').
                           paginate(page: current_page, per_page: 5)
  end

  private

  def find_user
    @user = User.find_by(login: params[:id])
  end

  def current_page
    if params['page']
      params['page'].to_i
    else
      1
    end
  end
end

app/helpers/gebruiker_helper.rb
module GebruikerHelper
end

app/views/gebruiker/edits.html.erb
<% if @definition_versions.size > 0 %>

  <%= will_paginate @definition_versions %>

  <% @definition_versions.each do |definition_version| %>
    <%= render partial: 'definities/definition_version', object: definition_version %>
  <% end %>

  <%= will_paginate @definition_versions %>

<% else %>

  <p>Deze gebruiker heeft nog geen bijdragen geleverd aan het Vlaams woordenboek.</p>

<% end %>

app/views/gebruiker/index.html.erb
<p>
	Er zijn momenteel <%= User.count %> gebruikers geregistreerd op het Vlaams woordenboek. De meest recentelijk geregistreerde
	gebruikers zijn
	<%= safe_join(@recentusers.map { |user| link_to(user.login, user_path(user.login)).html_safe }, ', ') %>.
</p>

<h2>Top bewerkers</h2>

<p>De volgende gebruikers hebben de meeste bewerkingen uitgevoerd aan de definities van het Vlaams woordenboek.</p>

<p>
<table class="barChart">
	<tr>
		<th width="0%">
		</th>
		<th width="30%">
			Gebruiker
		</th>
		<th width="70%">
			Bewerkingen
		</th>
	</tr>
	<% count = 0 %>
	<% maxc = Float( @topeditors.first[ "c" ] ) %>
	<% for topeditor in @topeditors %>
		<tr>
			<td align="right">
				<%= count = count + 1 %>
			</td>
			<td>
				<%=
					login = User.find( topeditor[ "updated_by" ] ).login
					link_to login, user_path(login)
				%>
			</td>
			<td class="quantifier">
				<%
					width = 5 + 90 * Float( topeditor[ "c" ] ) / maxc
				%>
    			<div style="width:<%= width.to_i %>%;">
      				<span><%= topeditor[ "c" ] %></span>
    			</div>
 			</td>
		</tr>
	<% end %>
</table>
</p>

<h2>Actiefste gebruikers</h2>

<p>De volgende gebruikers hebben in de afgelopen week de meeste bewerkingen aan het Vlaams woordenboek uitgevoerd.</p>

<p>
<table class="barChart">
	<tr>
		<th width="0%">
		</th>
		<th width="30%">
			Gebruiker
		</th>
		<th width="70%">
			Bewerkingen in laatste week
		</th>
	</tr>
	<% count = 0 %>
	<% maxc = Float( @activeeditors.first[ "c" ] ) %>
	<% for topeditor in @activeeditors %>
		<tr>
			<td align="right">
				<%= count = count + 1 %>
			</td>
			<td>
				<%=
					login = User.find( topeditor[ "updated_by" ] ).login
					link_to login, user_path(login)
				%>
			</td>
			<td class="quantifier">
				<%
					width = 5 + 90 * Float( topeditor[ "c" ] ) / maxc
				%>
    			<div style="width:<%= width.to_i %>%;">
      				<span><%= topeditor[ "c" ] %></span>
    			</div>
 			</td>
		</tr>
	<% end %>
</table>
</p>

<h2>Top commentatoren</h2>

<p>De volgende gebruikers hebben het meest gereageerd op definities van het Vlaams woordenboek.</p>

<p>
<table class="barChart">
	<tr>
		<th width="0%">
		</th>
		<th width="30%">
			Gebruiker
		</th>
		<th width="70%">
			Reacties
		</th>
	</tr>
	<% count = 0 %>
	<% maxc = @topreactors.empty? ? 1 : Float( @topreactors.first[ "c" ] ) %>
	<% for topreactor in @topreactors %>
		<tr>
			<td align="right">
				<%= count = count + 1 %>
			</td>
			<td>
				<%=
					login = User.find( topreactor[ "created_by" ] ).login
					link_to login, user_path(login)
				%>
			</td>
			<td class="quantifier">
				<%
					width = 5 + 90 * Float( topreactor[ "c" ] ) / maxc
				%>
    			<div style="width:<%= width.to_i %>%;">
      				<span><%= topreactor[ "c" ] %></span>
    			</div>
 			</td>
		</tr>
	<% end %>
</table>
</p>

app/views/gebruiker/reactions.html.erb
<% if @reactions.size > 0 %>

  <%= will_paginate @reactions %>

  <% @reactions.each do |reaction| %>
    <h2>
      <% if reaction.definition %>
        <%= link_to reaction.definition.word, definition_path(reaction.definition) %>
      <% else %>
        -
      <% end %>
    </h2>
    <%= render partial: "definities/reaction", object: reaction %>
  <% end %>

  <%= will_paginate @reactions %>

<% else %>

  <p>Deze gebruiker heeft nog geen reacties geschreven.</p>

<% end %>

app/views/gebruiker/show.html.erb
<div class="caption">Geregistreerd sinds <%= localize( @user.created_at ) %></div>

<% if logged_in? && @user != current_user %>
	<p>&#187; <%= link_to "Schrijf een bericht naar deze gebruiker", new_post_path(to: @user.login) %></p>
<% end %>

<% if !@user.details.blank? %>
	<h2>Over mezelf</h2>
	<%= format_user_content(@user.details) %>
<% else %>
	<% if logged_in? && @user == current_user %>
		<h2>Over mezelf</h2>
		In uw <%= link_to( "instellingen", edit_account_path) %> kunt ge iets schrijven over
		uzelf, en dat wordt dan hier weergegeven.
	<% end %>
<% end %>

<h2>Recentste wijzigingen</h2>

<p><%= link_to "Bekijk alle (#{@user.definition_versions.size}) wijzigingen van deze gebruiker.", edits_user_path(@user.login) %></p>

<% if @definition_versions.size > 0 %>

	<% @definition_versions.each do |definition_version| %>
		<% if definition_version.definition %>
			<%= render partial: "definities/definition_version", object: definition_version %>
		<% end %>
	<% end %>

<% else %>

	<p>Deze gebruiker heeft nog geen bijgedragen geleverd aan het Vlaams woordenboek.</p>

<% end %>

<h2>Recente reacties</h2>

<p><%= link_to "Bekijk alle (#{@user.reactions.size}) reacties van deze gebruiker.", reactions_user_path(@user.login) %></p>

<% if @reactions.size > 0 %>

	<% @reactions.each do |reaction| %>
		<% if reaction.definition %>
			<h2><%= link_to reaction.definition.word, definition_path(reaction.definition) %></h2>
			<%= render partial: "definities/reaction", object: reaction %>
		<% end %>
	<% end %>

<% else %>

	<p>Deze gebruiker heeft nog geen reacties geschreven.</p>

<% end %>