config/routes.rb
App::Application.routes.draw do
  root to: 'definities#index'

  resources :definitions, controller: 'definities',
                          path: 'definities',
                          only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'woordvandedag', as: :wotd, on: :collection
    get 'term/:term', as: :term, on: :collection, action: :term
    get 'search', as: :search, on: :collection, action: :search
    get 'begintmet/:prefix', as: :prefix, on: :collection, action: :prefix
    post 'autocomplete', on: :collection, action: :auto_complete_for_definition_q

    get 'random', as: :random, on: :collection, action: :random
    get 'top', as: :top, on: :collection, action: :top
    get 'recent', as: :recent, on: :collection, action: :recent

    get 'wijzigingen', as: :recent_edits, on: :collection, action: :wijzigingen
    get 'reacties', as: :recent_reactions, on: :collection, action: :reacties

    get 'geschiedenis', as: :history, on: :member, action: :history
    post 'thumbsup', on: :member, action: :thumbsup

    # TODO: reactions should really be their own (sub) controller
    post 'reactie', as: :post_reaction, on: :member, action: :add_reaction
    delete 'reactie/:reaction_id', as: :reaction, on: :collection, action: :delete_reactie

    post 'newwotd', as: :new_wotd, on: :member, action: :new_wotd
  end

  resource :info, controller: 'info', only: [:show] do
    get :contact, on: :collection
    get :regios, on: :collection
    get :feeds, on: :collection
    get :updates, on: :collection
  end

  post 'login', controller: :account, as: :login
  get 'login', controller: :account
  get 'logout', controller: :account, as: :logout
  resource :account, controller: 'account', only: [:new, :create, :edit, :update]

  resources :users, controller: 'gebruiker', id: /.*/, only: [:index] do
    get 'wijzigingen', as: :edits, on: :member, action: :edits
    get 'reacties', as: :reactions, on: :member, action: :reactions
  end
  get '/users/:id' => 'gebruiker#show', as: :user, id: /.*/

  resources :posts, controller: 'post', only: [:index, :new, :create, :show] do
    get 'outbox', as: :outbox, on: :collection, action: :outbox
  end

  get '/recent.xml' => 'definities#recent_rss'
  get '/wijzigingen.xml' => 'definities#wijzigingen_rss', as: :recent_edits_rss
  get '/woordvandedag.xml' => 'definities#woordvandedag'

  get 'robots.txt' => 'utils#robots'
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def show
    @title = "Achtergrond bij het Vlaams Woordenboek"
  end

  def regios
    @title = "Vlaamse provincies en regio's"
  end

  def contact
    @title = "Contacteer ons"
  end

  def feeds
    @title = "RSS Feeds"
  end

  def updates
    @title = "Updates"
  end

  def voorwaarden
    @title = "Algemene Voorwaarden"
  end

  def uitspraak
    @title = "Uitspraakweergave"
  end
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/_secondarymenu.html.erb
<p>
	<%= link_to 'Achtergrond', info_path %> &nbsp;|&nbsp;
	<%= link_to "Updates", updates_info_path %> &nbsp;|&nbsp;
	<%= link_to "Provincies en Regio's", regios_info_path %> &nbsp;|&nbsp;
	<%= link_to "RSS Feeds", feeds_info_path %> &nbsp;|&nbsp;
	<%= link_to "Contact", contact_info_path %>
</p>

app/views/info/contact.html.erb
<p>Het online Vlaams woordenboek wordt verzorgd door <a href="http://anthony.liekens.net">Anthony Liekens</a>.</p>

<p>Ge kunt het Vlaams woordenboek contacteren door een e-mail te sturen naar
<a href="mailto:anthony@liekens.net">anthony@liekens.net</a>, of via de post:</p>

<p>
	Het Vlaams woordenboek<br/>
	p/a dr. Anthony Liekens<br/>
	Manebruggestraat 366<br/>
	2150 Borsbeek
</p>

app/views/info/feeds.html.erb
<p>De volgende <a href="http://nl.wikipedia.org/wiki/Webfeed">RSS webfeeds</a> van het Vlaams woordenboek zijn momenteel beschikbaar:</p>

<ul>
<li><a href="/woordvandedag.xml">Vlaams woord van de dag <img src="/images/rss.png" alt="RSS"/></a></li>
<li><a href="/recent.xml">Recente toevoegingen <img src="/images/rss.png" alt="RSS"/></a></li>
</ul>

app/views/info/regios.html.erb
<p>Het online Vlaams woordenboek wil op de eerste plaats een verzameling bouwen van "Algemeen Beschaafd Vlaamse" woorden, woorden die
door zo goed als elke Vlaming worden begrepen. Het Vlaams is echter sterk versnipperd in een grote variëteit aan dialecten.
Dialecttermen nemen een belangrijke taak op in het dagelijks gesproken Vlaams, en krijgen daarom ook hun plaats in het online Vlaams
woordenboek. Als ge als gebruiker een Vlaamse term in onze databank steekt, kunt ge bij uw beschrijving aangeven uit welke streek
de dialectterm afkomstig is.</p>

<p>De onderstaande kaarten geven de regio's weer die in het Vlaams woordenboek worden onderscheiden</p>

<center><img src="/images/vlaamse_provincies_en_regios.png"/></center>

<p>Er zijn 5 overheersende Vlaamse dialecten, wier streken van oorsprong sterk overeenkomen met de provinciegrenzen; West-Vlaams, Oost-Vlaams, Antwerps,
Brabants and Limburgs.</p>

<p>Daarnaast zijn er binnen elke provincie lokale regio's met hun eigen dialect. Twee naburige dorpen kunnen sterke verschillen in hun
dialect vertonen. Om het woordenboek echter niet te overladen met keuzemogelijkheden, beperken we de classificatie tot dialecten, zoals
gesproken in hun overeenkomstige toeristische regio's van Vlaanderen. De volgende regio's zijn opgenomen in het Vlaams woordenboek.</p>

<ul><li>Province West-Vlaanderen
<ul><li>Vlaamse kust
</li><li>Westhoek
</li><li>Brugge
</li><li>Brugse Ommeland
</li><li>Leiestreek
</li></ul></li><li>Provincie Oost-Vlaanderen
<ul><li>Meetjesland
</li><li>Gent
</li><li>Vlaamse Ardennen
</li><li>Scheldeland
</li><li>Waasland
</li></ul></li><li>Provincie Antwerpen
<ul><li>Antwerpen
</li><li>Mechelen
</li><li>Antwerpse Kempen
</li></ul></li><li>Provincie Vlaams-Brabant
<ul><li>Brussel
</li><li>Groene Gordel
</li><li>Leuven
</li><li>Hageland
</li></ul></li><li>Provincie Limburg
<ul><li>Limburgse Kempen
</li><li>Mijnstreek
</li><li>Haspengouw
</li><li>Maasland
</li><li>Voerstreek
</li></ul></li></ul>

app/views/info/show.html.erb
<h2>Algemeen Beschaafd Vlaams</h2>

<p>Zelfs na 7 jaar als Vlaming te werken in een Nederlands team, ontdek ik samen met mijn collega's nog dagelijks woorden die in het
Vlaams en in het Nederlands anders zijn. Luister naar de radio of televisie in Vlaanderen, en er wordt <i>Vlaams</i>, <i>Belgisch
Nederlands</i>, <i>Vlaams Nederlands</i> of <i>Algemeen Beschaafd Vlaams</i> gesproken (<%= link_to 'noem', term_definitions_path(term: 'noeman') %>
het zoals u wilt, wij kiezen hier voor <i>Vlaams</i>, maar dat is zeker niet uit separatistische, Vlaams nationalistische of anti-
<%= link_to 'Belgicistische', term_definitions_path(term: 'Belgicist') %> overwegingen!).</p>

<p>De gemiddelde Nederlander heeft niks aan <a href="http://www.een.be/flikken/">Flikken</a> of <a
href="http://www.een.be/witse/">Witse</a> zonder ondertiteling, terwijl deze in Vlaanderen perfect kunnen worden
<%= link_to 'verstaan', term_definitions_path(term: 'verstaan') %>. Vlaams klinkt voor een Nederlander zacht en grappig, maar ook boertig en dom.
Nederlands klinkt voor een Belg hard en fleurig, maar ook elitair, burgerlijk of <%= link_to 'jaennet', term_definitions_path(term: 'jeannet') %>terig.
In vergelijking met het officiëlere Nederlands gebruiken we in Vlaanderen een woordenschat die op veel punten verschilt en anders
wordt uitgesproken, zinnen die anders worden opgebouwd en vervoegd, spreuken die verschillen, enzovoort. Dit gebeurt in zo'n grote
mate dat goed ingeburgerd Vlaams heel snel complete nonsens wordt voor andere Nederlandstaligen.</p>

<div class="block" style="color:#666;">

<h3>Voorbeeldje: Goesting</h3>

<p>Eind 2004 verkozen de Vlamingen <i><%= link_to 'goesting', term_definitions_path(term: 'goesting') %></i> tot het mooiste woord van de Nederlandse
taal. Meer dan 3000 luisteraars van <a href="http://www.radio1.be">Radio 1</a> gaven hun stem tijdens de finale stemronde. In een
gelijkaardige verkiezing in Nederland werd <i>liefde</i> gekozen als mooiste woord.</p>

<p>Opvallend is dat <i>goesting</i> Belgisch Nederlandse spreektaal is, en niet wordt aangezien als <i>standaardtaal</i>. Het woord is
volkomen ingeburgerd in Vlaanderen, maar de gemiddelde Nederlander heeft geen idee dat dit woord sowieso bestaat. <i>Goesting</i>
heeft <i>trek</i>, <i>zin</i> of <i>lust</i> als Nederlandse synoniemen. De oorprong van het woord is het Latijnse <i>gustus</i>
(smaak), en kwam via het Frans naar Vlaanderen. Ook komt het woord voor in tal van Vlaamse uitdrukkingen, zoals <i>ieder zijn
goesting</i> (ieder kiest wat hij het liefste wil), <i>zijn goesting gegeten hebben</i> (voldaan zijn), of <i>met zijn broek vol
goesting rondlopen</i> (zin in sex hebben).</p>

</div>


<h3>Vlaams &lt; Nederlands?</h3>

<p>Woordenboeken en taalregels die het <i>officiële</i> Nederlands vertegenwoordigen beschouwen het Vlaams nogal gemakkelijk als
minderwaardig ten opzichte van het Nederlands Nederlands (Nederlands zoals het gebruikt wordt in Nederland). In <a
href="http://taalschrift.org/discussie/001516.html">dit artikel</a> (taalschrift.org) stelt <a
href="http://www.nederlandsetaalkunde.ugent.be/Prof.%20Dr.%20Johan%20De%20Caluwe">prof. dr. Johan De Caluwe</a> van de universiteit
Gent dat Belgisch Nederlands en Nederlands Nederlands evenwaardige varianten van het Nederlands zijn, net zoals Brits Engels en
Amerikaans Engels varianten van het Engels zijn. In Nederlandse woordenboeken of de regels die opgesteld worden door <i>officiële</i>
Nederlandse instituten wordt het Nederlands Nederlands echter als het correcte Nederlandse taalgebruik onderschreven en vervallen
goed ingeburgerde Vlaamse gebruiken al snel buiten de boot. Dit elitair gedrag is discriminerend voor het Vlaams, en Nederlanders
krijgen op deze manier al snel het comfortabele gevoel dat hun Nederlands Nederlands correct en ons Belgisch Nederlands incorrect
taalgebruik is. </p>

<div class="block" style="color:#666;">

<h3>Voorbeeldje: Wat is uw nationaliteit?</h3>

<img src="/images/identiteitskaart.jpg" style="float:right;"/> <p>Vraag de gemiddelde Nederlander naar zijn nationaliteit, en hij
antwoordt steevast <i>Nederlandse</i> (de TaalUnie <a href="http://www.onzetaal.nl/advies/nationaliteit.php">adviseert</a> trouwens
<i>Nederlands</i>, TaalAdvies dan weer <a href="http://taaladvies.net/taal/advies/vraag/570/">niet</a>). Een Belg antwoordt op deze
vraag met <i>Belg</i>. Echter verwacht de Belg dat de Nederlander hierop <i>Nederlander</i> zou antwoorden, en vice versa denkt de
Nederlander dat het correcte antwoord voor de Belg <i>Belgisch(e)</i> moet zijn. Zo ook vult de Nederlandse loketbediende van mijn
Vlaamse <%= link_to 'mutualiteit', term_definitions_path(term: 'mutualiteit') %> <i>Belgische</i> in in het veld <i>nationaliteit</i> van mijn
formulieren. Zijn we dan in Vlaanderen allemaal verkeerd bezig met onze nationaliteit? Zelfs (Nederlandstalige) Belgische
identiteitskaarten geven aan dat onze nationaliteit <i>Belg</i> is. Een taalfout? Ik denk het niet! Het gebruik van Belg/Nederlander
is in zijn Belgische context even correct als Nederlandse/Belgische in een Nederlandse context.</p>

</div>

<p>Ook geeft prof. De Caluwe aan dat Nederlands Nederlandse woorden moeten worden geannoteerd in woordenboeken, net zoals Belgisch
Nederlandse woorden worden geannoteerd. Op deze manier wordt het voor de gebruiker van een woordenboek duidelijk of een Nederlands
woord een specifieke betekenis heeft die enkel in Nederland zo wordt gebruikt. Ik kan dit standpunt alleen maar toejuichen!</p>

<div class="block" style="color:#666;">

<h3>Voorbeeldje uit de <a href="http://www.vandale.be">Van Dale</a></h3>

<p>Het volgende woord vind ik het schoolvoorbeeld van hoe verschillend de Vlaamse en Nederlandse betekenis van een woord wel niet kan
zijn (mijn excuses voor de woordkeuze, het is niet echt een <i>school</i>voorbeeld).</p>

<p style="margin-left:20px;"><i>
poe·pen (onov.ww.)<br/>
1 [inf.] lichamelijke afvalstoffen uitscheiden via de anus [...]<br/>
2 [Belg., grof] neuken, vrijen
</i></p>

<p>In de Van Dale staat bij de Belgische betekenis van <i><a
href="http://vandale.be/opzoeken/woordenboek/?zoekwoord=poepen">poepen</a></i> (grof voor neuken, vrijen) de annotatie <i>[Belg.]</i>,
maar bij de Nederlandse betekenis (afvalstoffen uitscheiden) wordt niet vermeld dat deze betekenis voornamelijk in Nederland wordt
gebruikt, en ongebruikelijk is voor Vlaanderen. Er zijn wel honderden van dit soort vermeldingen in de Van Dale die op deze manier
kunnen worden aangemerkt. De licht gewijzigde versie is al een pak beter:</p>

<p style="margin-left:20px;"><i>
poe·pen (onov.ww.)<br/>
1 [<b>Ned.</b>, inf.] lichamelijke afvalstoffen uitscheiden via de anus [...]<br/>
2 [Belg., grof] neuken, vrijen
</i></p>

<p>De context rond <i>poepen</i> krijgt een heel andere draai bij een Vlaams of Nederlands publiek. Om te laten zien hoe fout dit kan
aflopen, citeer ik het volgende gedichtje uit mijn zoontje's <a href="http://www.vandale.nl/producten/1001004002496337">Mijn eerste
Van Dale</a> (volgens de omschrijving een boek voor 2-3 jarigen), bij het woord <i>poepen</i> (met tekening van lief klein meisje op
de wc):</p>

<p style="margin-left:20px;"><i>
Winnie zit op de wc.<br/>
Haar billetjes zijn bloot.<br/>
En weet je wat ze roept?<br/>
Mama, ik heb gepoept!
</i></p>

<p>Wat heeft Winnie gedaan? Gepoept??? U kan zich waarschijnlijk al inbeelden hoe de gemiddelde Vlaming (met
pedofilie-massahysterie-syndroom) bij het lezen van dit gedichtje uit zijn stoel valt!</p>

<p>Update: De redacteurs van de Van Dale hebben bevestigd dat de volgende
versie van hun woordenboeken deze wijziging zullen doorvoeren, zoals
aangegeven in het <a
href="http://www.deredactie.be/cm/vrtnieuws/cultuur%2Ben%2Bmedia/kunsten/091105VanDaleNederlands">VRT
nieuws van 6 november 2009</a>.</p>

</div>

<p>Zo ook zouden verschillen in uitspraak (voor bijvoorbeeld tram, caravan, camping, therapeut, ...) kunnen worden geannoteerd in deze
woordenboeken. Er zijn heel wat van die termen waar Nederlanders hun uitspraken voor baseren op Engelse versie van deze woorden
(bvb [ˈkærəˌvæn] voor caravan), waar Vlamingen hun uitspraak op het Frans baseren (bvb [ˈkaraˌvan] voor caravan).</p>

<h3>Het Vlaams woordenboek</h3>

<p>Op deze website willen we de pareltjes van onze Vlaamse variant van het Nederlands eens goed in de verf zetten. Het Vlaams heeft
vele mooie, charmante en <%= link_to 'plezante', term_definitions_path(term: 'plezant') %> woorden en uitdrukkingen die dikwijls te beperkt worden
gerepresenteerd door de officiële Nederlandse woordenboeken en taalregeltjes.</p>

<p>Geïnspireerd door de ideeën van de Engelstalige <a href="http://www.urbandictionary.com">Urban Dictionary</a> stelt het online
Vlaams woordenboek elke Vlaming (en andere Nederlandstaligen) in staat om deel te nemen aan het schrijven en bouwen van een
woordenlijst van typisch Vlaamse woorden en uitspraken, als aanvullingen en correcties op het <i>officiële</i> (Nederlands-)
Nederlands. Taal is geen gegeven dat bepaald wordt door een stel elitaire professoren, maar is het resultaat van een langdurig
democratisch proces dat zich in het volk zelf af speelt. Sommige hooggeleerden mogen dan wel vinden dat typisch Vlaamse taalkenmerken
(gebruik van <i>ge</i> of <i>gij</i>, verbogen werkwoorden en dubbelklanken die het Vlaams voor een buitenstaander moeilijker te
begrijpen maken) uit ons taalgebruik moeten worden verbannen, als ze het volk niet achter deze opinie geschaard krijgen zal er niet
snel iets veranderen. Taal is een complex dynamisch proces dat zich niet snel zal laten leiden door van bovenaf opgelegde regels!
Naar wat ik hoor van mijn buitenlandse collega's (die Nederlands studeren) vinden zij het Belgisch Nederlands in elk geval een pak
gemakkelijker te verstaan dan het Nederlands Nederlands. Met het Vlaams woordenboek proberen we dit democratisch, volks proces in een
website te gieten, zodat iedereen in staat is om zijn eigen taal mee te definiëren!</p>

<p>Het Vlaams woordenboek bevat reeds honderden definities van Vlaamse termen. Op onze <%= link_to 'thuispagina', root_path %> kan u de index
bekijken, willekeurige Vlaamse woorden uit ons woordenboek opvragen, en recente toevoegingen aan het Vlaams woordenboek opvolgen. We
roepen dagelijks ook een Vlaams woord uit tot <%= link_to 'Vlaams woord van de dag', random_definitions_path %>. Elke bezoeker van het
Vlaams woordenboek kan ook bijdragen door mee te stemmen welke definities hij goed of slecht vindt. Meer nog, als u uzelf <%= link_to 'registreert', new_account_path %>
als gebruiker van deze website, kan u nieuwe (of verbeterde) definities van allerhande
Vlaamse woorden toevoegen aan onze databank, en reageren op de definities van andere gebruikers.</p>

<p>Er valt al heel wat te bekijken op deze nieuwe website, ik wens u in alle geval veel Vlaams taalplezier!</p>
<p><a href="http://anthony.liekens.net">Anthony Liekens</a>,-</p>

app/views/info/updates.html.erb
<h2>14 januari 2008: Social networking, en we staan in de Libelle</h2>

<p>Er zijn de afgelopen dagen een aantal updates gebeurd aan het Vlaams woordenboek. Vooral de gebruikers worden nu beter gehuisvest
en krijgen een aantal nieuwe "social networking" tools in de handen geduwd. Zo kunt ge nu als ingelogd gebruiker iets over uzelf
vertellen op uw eigen profielpagina, en is er nu een intern postsysteem zodat contact tussen geregistreerde
gebruikers van het Vlaams woordenboek mogelijk wordt.</p>

<p>De (Belgische) <a href="http://www.libelle.be">Libelle</a> heeft deze week (10 januari 2008) een <a
href="/images/libelle10jan08.png">kort stukje</a> op zijn vierde pagina gezet, met niks dan goeie woorden voor het Vlaams woordenboek.
De Libelle is wel heel wat anders dan ik gewoon ben, maar ik ben dolblij dat ik nu eens iets kan doen voor andere mensen dan enkel en
alleen techneuten!</p>

<h2>15 november 2007: Het Vlaams woordenboek wordt een wiki</h2>

<p>Het Vlaams woordenboek heeft zonet een belangrijke facelift gekregen. Veel gebruikers hebben de wens uitgesproken om andermans
definities te kunnen bewerken. Alle definities kunnen nu worden aangepast door ingelogde gebruikers, en er wordt een
bewerkingsgeschiedenis bijgehouden zodat de bijdragen van verschillende gebruikers van een woord kunnen worden opgevolgd. In feite is
het Vlaams woordenboek dus nu een soort van wiki geworden, die meer samenwerking van alle gebruikers mogelijk maakt. Ook kunnen nu
spellings- en grammaticafouten veel vlotter worden verbeterd, wat alleen maar kan leiden tot een meer kwaliteitsvol Vlaams
woordenboek.</p>

<p>Als gevolg van deze aanpassing zijn er ook een aantal andere elementen veranderd. Zo is nu de definitie van een term niet meer in
het bezit van 1 gebruiker, omdat meerdere gebruikers bijdragen kunnen leveren aan een en hetzelfde woord. Termen en hun definities
kunnen ook niet meer door hun respectieve eigenaars worden verwijderd. In een gebruikerspagina worden nu ook de woorden weergegeven
waaraan de gebruiker heeft meegewerkt. De pagina's die voorheen recente toevoegingen toonden, geven nu recente wijzigingen aan.</p>

<h2>14 november 2007: Het Vlaams woordenboek staat in het Laatste Nieuws</h2>

<p>In <a href="http://www.hln.be">Het Laatste Nieuws</a> is er een <a href="/images/hln14nov07.png">kort artikel</a> verschenen over het
Vlaams woordenboek.</p>

<h2>26 oktober 2007: Het Vlaams woordenboek gaat van start!</h2>

<p>Na een paar weekjes programmeren en designen, is het Vlaams woordenboek klaar om gelanceerd te worden voor het publiek. Er staan al
een pak woorden in vermeld van bij de start. De basiselementen van de website werken, maar het zal nog weken duren vooraleer er een
volwassen, vlot werkende service zal zijn.</p>