config/routes.rb
App::Application.routes.draw do
  root to: 'definities#index'

  resources :definitions, controller: 'definities',
                          path: 'definities',
                          only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get 'woordvandedag', as: :wotd, on: :collection
    get 'term/:term', as: :term, on: :collection, action: :term
    get 'search', as: :search, on: :collection, action: :search
    get 'begintmet/:prefix', as: :prefix, on: :collection, action: :prefix
    post 'autocomplete', on: :collection, action: :auto_complete_for_definition_q

    get 'random', as: :random, on: :collection, action: :random
    get 'top', as: :top, on: :collection, action: :top
    get 'recent', as: :recent, on: :collection, action: :recent

    get 'wijzigingen', as: :recent_edits, on: :collection, action: :wijzigingen
    get 'reacties', as: :recent_reactions, on: :collection, action: :reacties

    get 'geschiedenis', as: :history, on: :member, action: :history
    post 'thumbsup', on: :member, action: :thumbsup

    # TODO: reactions should really be their own (sub) controller
    post 'reactie', as: :post_reaction, on: :member, action: :add_reaction
    delete 'reactie/:reaction_id', as: :reaction, on: :collection, action: :delete_reactie

    post 'newwotd', as: :new_wotd, on: :member, action: :new_wotd
  end

  resource :info, controller: 'info', only: [:show] do
    get :contact, on: :collection
    get :regios, on: :collection
    get :feeds, on: :collection
    get :updates, on: :collection
  end

  post 'login', controller: :account, as: :login
  get 'login', controller: :account
  get 'logout', controller: :account, as: :logout
  resource :account, controller: 'account', only: [:new, :create, :edit, :update]

  resources :users, controller: 'gebruiker', id: /.*/, only: [:index] do
    get 'wijzigingen', as: :edits, on: :member, action: :edits
    get 'reacties', as: :reactions, on: :member, action: :reactions
  end
  get '/users/:id' => 'gebruiker#show', as: :user, id: /.*/

  resources :posts, controller: 'post', only: [:index, :new, :create, :show] do
    get 'outbox', as: :outbox, on: :collection, action: :outbox
  end

  get '/recent.xml' => 'definities#recent_rss'
  get '/wijzigingen.xml' => 'definities#wijzigingen_rss', as: :recent_edits_rss
  get '/woordvandedag.xml' => 'definities#woordvandedag'

  get 'robots.txt' => 'utils#robots'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

		<title>Het Vlaams woordenboek <% if @title %>&#187; <%= @title %><% end %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application' %>
		<%= javascript_include_tag 'application' %>
		<link rel="alternate" type="application/rss+xml" title="Vlaams woord van de dag" href="/woordvandedag.xml" />

		<% if ENV['VLAAMSWOORDENBOEK_BETA'] %>
			<meta name="robots" content="noindex, nofollow">
		<% end %>
	</head>
<body>
	<% if ENV['VLAAMSWOORDENBOEK_BETA'] %>
		<div class="beta-badge">
			<i class="left"></i>
			<i class="right"></i>
			<%= ENV['VLAAMSWOORDENBOEK_BETA'] %>
		</div>
	<% end %>

	<div id="leftcontent">

		<%= link_to root_path do %>
			<img src="/images/boek.png" style="float:left;padding:10px 10px 0px 10px;" alt="Vlaams Woordenboek logo"/>
		<% end %>
		<center><h2 style="padding: 10px 0px 0px 0px;"><%= link_to 'Het Vlaams woordenboek', root_path, style: "color:#333;" %></h2></center><br/>

		<div class="block">
			<h2>Index</h2>
			<p>
				<% ('A'..'Z').each do |letter| %>
					<%= link_to letter, prefix_definitions_path(prefix: letter.downcase) %>
				<% end %>
			</p>
		</div>

		<%=render :partial => 'leftcolumn'%>

		<div class="block">
			<%= render :partial => "account/login" %>
		</div>

	</div>

	<div id="centercontent">

		<div id="primarymenu">
			<% if logged_in? %>
				<div style="float:right;"><li><%= link_to 'Nieuw woord', new_definition_path %></li></div>
			<% else %>
				<div style="float:right;"><li><%= link_to 'Log in', login_path -%></li></div>
			<% end %>
			<ul>
				<li><%= link_to 'Woordenboek', definitions_path %></li>
				<li><%= link_to 'Woord van de dag', wotd_definitions_path %></li>
				<li><%= link_to 'Gebruikers', users_path %></li>
				<li><%= link_to 'Info', info_path %></li>
			</ul>
		</div>

		<% if @trail %>
			<p style="float:right;"><%= @trail %></p>
		<% end %>

		<%= render :partial => "secondarymenu"%>

		<h1>
			<%= @title %>
		</h1>

		<p style="color: green"><%= flash[:notice] %></p>


		<%= yield  %>

	</div>

	<div id="rightcontent">

		<div class="block block-search">
			<p>
				<center>
					<%= form_tag search_definitions_path, method: :get do %>
					<%= text_field_with_auto_complete :definition, :q, { :size => 15, :value => "" }, { url: autocomplete_definitions_path } %>
					<%= submit_tag 'Zoek' %>
					<% end %>
				</center>
			</p>
		</div>

		<% if logged_in? && current_user.inbox_size > 0 %>
			<div class="block">
				<h2>Berichten</h2>
				<p>Er zijn nieuwe berichten (<%=current_user.inbox_size%>) in uw <%= link_to 'postvak', posts_path %></p>
			</div>
		<% end %>

		<div class="block">
			<p class="center">
				<b>Nieuwe versie!</b><br/>
				Er is een nieuwe versie van het Vlaams Woordenboek online. Mocht je problemen ondervinden, gelieve deze te melden op onze
					<a href="https://github.com/vlaamswoordenboek/vlaamswoordenboek.be/issues">GitHub</a>.
			</p>
		</div>

		<% if logged_in? && current_user.admin? %>
			<div class="block-admin">
				<p class="center">Ingelogd als admin</p>
			</div>

			<div class="block">
				<h2>Nuttige links</h2>

				<ul class="menu">
					<li><%= link_to 'Recente wijzigingen', recent_edits_definitions_path %></li>
					<li><%= link_to 'Recente reacties', recent_reactions_definitions_path %></li>
				</ul>
			</div>

		<% else %>
			<div class="block">
				<p class="center">
					<script type="text/javascript"><!--
						google_ad_client = "pub-7726730941948502";
						google_ad_width = 160;
						google_ad_height = 600;
						google_ad_format = "160x600_as";
						google_ad_type = "text_image";
						//2007-09-16: vlaamswoordenboek
						google_ad_channel = "0642600976";
						google_color_border = "FFFFFF";
						google_color_bg = "FFFFFF";
						google_color_link = "2763A5";
						google_color_text = "444444";
						google_color_url = "AAAAAA";
						google_ui_features = "rc:0";
					//-->
					</script>
					<script type="text/javascript" src="https://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</p>
			</div>

		<% end %>

	</div>

	<p>
		<center style="color:#aaa;">
			Het Vlaams woordenboek &nbsp;|&nbsp;
			Concept en realisatie door <a href="http://anthony.liekens.net">Anthony Liekens</a> <br/><br/>
			<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br/><br/><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Dataset" property="dct:title" rel="dct:type">Het Vlaams Woordenboek</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://anthony.liekens.net" property="cc:attributionName" rel="cc:attributionURL">Anthony Liekens</a> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
		</center>
	</p>

	<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write("\<script src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'>\<\/script>" );
	</script>
	<script type="text/javascript">
	var pageTracker = _gat._getTracker("UA-3231609-1");
	pageTracker._initData();
	pageTracker._trackPageview();
	</script>

</body>
</html>